services:
  eter-anime-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eter-anime-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
